// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Puppeteer = require("puppeteer");
var AsciifyImage = require("asciify-image");

Puppeteer.launch({
          args: /* array */[
            "--no-sandbox",
            "--disable-gpu"
          ]
        }).then((function (browser) {
          return browser.newPage().then((function (page) {
                          return page.setViewport({
                                              width: 640,
                                              height: 640
                                            }).then((function (param) {
                                              return page.goto("https://via.placeholder.com/300");
                                            })).then((function (param) {
                                            return page.screenshot({
                                                        path: undefined
                                                      });
                                          })).then((function (buffer) {
                                          return AsciifyImage(buffer, {
                                                      fit: "box",
                                                      width: 100,
                                                      height: 100
                                                    });
                                        })).then((function (asciified) {
                                        console.log(asciified);
                                        return Promise.resolve(/* () */0);
                                      }));
                        })).then((function (param) {
                        return browser.close();
                      }));
        })).catch((function (error) {
        console.log(error);
        return Promise.resolve(/* () */0);
      }));

/*  Not a pure module */
