// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Puppeteer = require("puppeteer");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var ThumbnailNotCreated = Caml_exceptions.create("Screenshot-NewProject.ThumbnailNotCreated");

function takeScreenshot(url, fullPage, width, height) {
  return Puppeteer.launch({
                  args: /* array */[
                    "--no-sandbox",
                    "--disable-gpu"
                  ]
                }).then((function (browser) {
                  return browser.newPage().then((function (page) {
                                return page.setViewport({
                                                    width: width,
                                                    height: height,
                                                    isMobile: true,
                                                    deviceScaleFactor: 2
                                                  }).then((function (param) {
                                                    return page.goto(url);
                                                  })).then((function (param) {
                                                  return new Promise((function (resolve, param) {
                                                                setTimeout((function (param) {
                                                                        return resolve(undefined);
                                                                      }), 2000);
                                                                return /* () */0;
                                                              }));
                                                })).then((function (param) {
                                                return page.screenshot({
                                                            path: undefined,
                                                            fullPage: fullPage
                                                          });
                                              })).then((function (buffer) {
                                              return browser.close().then((function (param) {
                                                            return Promise.resolve(buffer);
                                                          }));
                                            }));
                              }));
                })).catch((function (error) {
                console.log("Error creating thumbnail", error);
                return Promise.reject([
                            ThumbnailNotCreated,
                            /* () */0
                          ]);
              }));
}

function takeScreenshotDefault(url) {
  return takeScreenshot(url, false, 480, 480);
}

var P = 0;

var CH = 0;

exports.P = P;
exports.CH = CH;
exports.ThumbnailNotCreated = ThumbnailNotCreated;
exports.takeScreenshot = takeScreenshot;
exports.takeScreenshotDefault = takeScreenshotDefault;
/* puppeteer Not a pure module */
